org: philipwee
app: squash-weekly-poll
service: squash-weekly-poll

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x

useDotenv: true

functions:
  rateHandler:
    handler: dist/handler.run
    events:
      # 9am every saturday
      - schedule: cron(0 9 ? * SAT *)

plugins:
  - serverless-offline
